//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rheo.Storage.DefinitionsBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rheo.Storage.DefinitionsBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flf2a$ 8 8 17 -1 8
        ///basic.flf by Craig O&apos;Flaherty &lt;cofl@it.ntu.edu.au&gt;
        ///August 17, 1994
        ///
        ///---
        ///
        ///Font modified June 17, 2007 by patorjk 
        ///This was to widen the space character.
        ///
        ///$   $@
        ///$   $@
        ///$   $@
        ///$   $@
        ///$   $@
        ///$   $@
        ///$   $@
        ///$   $@@
        ///db$@
        ///88$@
        ///YP$@
        ///  $@
        ///db$@
        ///YP$@
        ///  $@
        ///  $@@
        ///.o. .o.$@
        ///`8&apos; `8&apos;$@
        ///       $@
        ///       $@
        ///       $@
        ///       $@
        ///       $@
        ///       $@@
        ///       $@
        /// db db $@
        ///C88888D$@
        /// 88 88 $@
        ///C88888D$@
        /// YP YP $@
        ///       $@
        ///       $@@
        ///   A   $@
        ///.d8888.$@
        ///88&apos;8 YP$@
        ///`8b8.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FigletBasicFont {
            get {
                return ResourceManager.GetString("FigletBasicFont", resourceCulture);
            }
        }
    }
}
